#!/bin/sh

echo "===== Pre-Commit ====="

pytest

if [ $? != 0 ]
then
    echo "Pre-Commit: Tests failed! Aborting the commit"
    exit 1
else
    echo "Tests ran successfully, committing..."
fi

exit 0