#!/bin/sh

echo "===== Pre-Commit ====="

echo "===== Running pytest ====="
pytest

if [ $? -ne 0 ]
then
    echo "Pre-Commit: Tests failed! Aborting the commit"
    exit 1
fi

echo "Tests ran successfully, committing..."